# Generated by Django 6.0 on 2025-12-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_default='', default='', max_length=200)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='image_about')),
                ('description', models.TextField(db_default='', default='')),
                ('short_description1', models.CharField(db_default='', default='', max_length=300)),
                ('title_headline1', models.CharField(db_default='', default='', max_length=100)),
                ('title_headline2', models.CharField(db_default='', default='', max_length=100)),
                ('title_headline3', models.CharField(db_default='', default='', max_length=100)),
                ('short_description2', models.TextField(db_default='', default='')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='image2_about')),
                ('video', models.CharField(db_default='', default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='slider',
            name='description',
            field=models.TextField(db_default='', default=''),
        ),
        migrations.AlterField(
            model_name='slider',
            name='title',
            field=models.CharField(db_default='', default='', max_length=200),
        ),
    ]
