# Generated by Django 6.0 on 2025-12-30 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0002_about_alter_slider_description_alter_slider_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_service', models.CharField(db_default='', default='', max_length=100)),
                ('title', models.CharField(db_default='', default='', max_length=100)),
                ('description', models.TextField(db_default='', default='', max_length='300')),
                ('speed', models.TextField(db_default='', default='', max_length=100)),
            ],
        ),
    ]
