# Generated by Django 6.0 on 2025-12-31 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0003_services'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Services',
            new_name='Service',
        ),
    ]
