# Generated by Django 6.0 on 2026-01-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0004_rename_services_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, db_default='', default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_service',
            field=models.CharField(blank=True, db_default='', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='speed',
            field=models.CharField(blank=True, db_default='', default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, db_default='', default='', max_length=100),
        ),
    ]
