# Generated by Django 6.0 on 2026-01-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0005_alter_service_description_alter_service_icon_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catigory', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('title', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('short_description', models.TextField(blank=True, db_default='', default='', max_length=300)),
                ('client', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('url', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('description', models.TextField(blank=True, db_default='', default='', max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_portfolio')),
            ],
        ),
    ]
