# Generated by Django 6.0 on 2026-02-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0006_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('role_company', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_team')),
                ('urlx', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('urlfacebook', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('urlinstagram', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('urllikedin', models.TextField(blank=True, db_default='', default='', max_length=100)),
                ('speed', models.TextField(blank=True, db_default='', default='', max_length=100)),
            ],
        ),
    ]
