# Generated by Django 6.0 on 2026-02-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0007_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('reply', models.TextField(blank=True, db_default='', default='', max_length=1000)),
                ('speed', models.CharField(blank=True, db_default='', default='', max_length=100)),
            ],
        ),
    ]
