# Generated by Django 6.0 on 2026-03-08 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0008_faq'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('email', models.EmailField(blank=True, db_default='', default='', max_length=100)),
                ('subject', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('message', models.TextField()),
                ('date_message', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
