# Generated by Django 6.0 on 2026-03-20 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companyapp', '0009_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generalsetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='image_favicon')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='image_logo')),
                ('companyname', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('email1', models.EmailField(blank=True, db_default='', default='', max_length=254)),
                ('email2', models.EmailField(blank=True, db_default='', default='', max_length=254)),
                ('phone', models.CharField(blank=True, db_default='', default='')),
                ('address', models.CharField(blank=True, db_default='', default='', max_length=200)),
                ('urlx', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('urlfacebook', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('urlinstagram', models.CharField(blank=True, db_default='', default='', max_length=100)),
                ('urllikedin', models.TextField(blank=True, db_default='', default='', max_length=100)),
            ],
        ),
    ]
